baseURL: "/"
languageCode: en-us
title: Revolution and Political Violence
theme: "ath-tufte-hugo_18-19"
googleAnalytics: ""
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - \.Rhistory$
  - \.yaml$
  - _files$
  - _cache$
  - \.csl$
  - \.Rproj.user/*
permalinks:
  post: "/:year/:month/:day/:slug/"
buildFuture: true
menu:
  main:
    - name: Syllabus
      url: /syllabus/
      weight: 1
    - name: Assignments
      url: /assignments/
      weight: 3
    - name: Schedule
      url: /schedule/
      weight: 2
    - name: Reference
      url: /reference/
      weight: 4
    - name: Slack
      url: "https://gitter.im/byustatsf18/"
      weight: 5
params: 
  author: Juan Tellez
  thumbnail: /images/POLI416.png
  instructor: 
    name: Juan Tellez
    email: juan.f.tellez@gmail.com
    url: "/"
    twitter: beingofbeings
    github: hail2thief
    office: NUMBER AND ROOM
  logo:
    url: /images/POLI416.png
    alt: Revolution and Political Violence
  course:
    number: POLI 416
    semester: Fall 2019
    days: "Tuesdays, Thursdays"
    time: "02:50-04:05 PM"
    location: "202 HUMCB"
    twitter: beingofbeings
    dates: "August 22–December 06, 2019"
    github: "hail2thief"
    copyrightYear: "2019"
    contactDetails: >-
      Office hours: [Sign up here.](https://calendly.com/juan-f-tellez)<br><br>E-mail is the best way to get in contact with me—I will respond to all course-related e-mails within 24 hours.
  university: 
    name: University of South Carolina
  school:
    name: Department of Political Science
  primaryColor: "#73000a"
  secondaryColor: "#CC2E40"
  credits: >-
    Course website design adapted/stolen from [Andrew Heiss](https://www.andrewheiss.com/). 
  meta:
    twitterSite: "@beingofbeings"
    twitterCreator: "@beingofbeings"
    fbAuthor: ""